# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/collection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromadb.server.grpc.models import metadata_pb2 as models_dot_metadata__pb2

from chromadb.server.grpc.models.metadata_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17models/collection.proto\x12\x0copenapitools\x1a\x15models/metadata.proto\"K\n\nCollection\x12\x0f\n\x04name\x18\x8b\xf5\xcd\x01 \x01(\t\x12\x0b\n\x02id\x18\x9b\x1a \x01(\t\x12\x1f\n\x08metadata\x18\xd1\x89\xca\xd6\x01 \x01(\x0b\x32\t.MetadataP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.collection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COLLECTION']._serialized_start=64
  _globals['_COLLECTION']._serialized_end=139
# @@protoc_insertion_point(module_scope)
