# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15models/metadata.proto\")\n\x08Metadata\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.KeyValueArray\")\n\rKeyValueArray\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.KeyValue\".\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value\"l\n\x05Value\x12\x13\n\tstr_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x42\x0c\n\nvalue_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_METADATA']._serialized_start=25
  _globals['_METADATA']._serialized_end=66
  _globals['_KEYVALUEARRAY']._serialized_start=68
  _globals['_KEYVALUEARRAY']._serialized_end=109
  _globals['_KEYVALUE']._serialized_start=111
  _globals['_KEYVALUE']._serialized_end=157
  _globals['_VALUE']._serialized_start=159
  _globals['_VALUE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
