# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from chromadb.server.grpc.services import default_service_pb2 as services_dot_default__service__pb2


class DefaultServiceStub(object):
    """rpc Add (AddRequest) returns (AddResponse);
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/openapitools.services.defaultservice.DefaultService/CreateCollection',
                request_serializer=services_dot_default__service__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=services_dot_default__service__pb2.Collection.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/openapitools.services.defaultservice.DefaultService/Heartbeat',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=services_dot_default__service__pb2.HeartbeatResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/openapitools.services.defaultservice.DefaultService/Reset',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=services_dot_default__service__pb2.ResetResponse.FromString,
                )
        self.Root = channel.unary_unary(
                '/openapitools.services.defaultservice.DefaultService/Root',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=services_dot_default__service__pb2.RootResponse.FromString,
                )
        self.Version = channel.unary_unary(
                '/openapitools.services.defaultservice.DefaultService/Version',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=services_dot_default__service__pb2.VersionResponse.FromString,
                )


class DefaultServiceServicer(object):
    """rpc Add (AddRequest) returns (AddResponse);
    """

    def CreateCollection(self, request, context):
        """rpc Count (CountRequest) returns (CountResponse);

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """rpc Delete (DeleteRequest) returns (DeleteResponse);

        rpc DeleteCollection (DeleteCollectionRequest) returns (Collection);

        rpc Get (GetRequest) returns (GetResult);

        rpc GetCollection (GetCollectionRequest) returns (Collection);

        rpc GetNearestNeighbors (GetNearestNeighborsRequest) returns (QueryResult);

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """rpc ListCollections (google.protobuf.Empty) returns (ListCollectionsResponse);

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Root(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """rpc Update (UpdateRequest) returns (UpdateResponse);

        rpc UpdateCollection (UpdateCollectionRequest) returns (Collection);

        rpc Upsert (UpsertRequest) returns (UpsertResponse);

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DefaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=services_dot_default__service__pb2.CreateCollectionRequest.FromString,
                    response_serializer=services_dot_default__service__pb2.Collection.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=services_dot_default__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=services_dot_default__service__pb2.ResetResponse.SerializeToString,
            ),
            'Root': grpc.unary_unary_rpc_method_handler(
                    servicer.Root,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=services_dot_default__service__pb2.RootResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=services_dot_default__service__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openapitools.services.defaultservice.DefaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DefaultService(object):
    """rpc Add (AddRequest) returns (AddResponse);
    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openapitools.services.defaultservice.DefaultService/CreateCollection',
            services_dot_default__service__pb2.CreateCollectionRequest.SerializeToString,
            services_dot_default__service__pb2.Collection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openapitools.services.defaultservice.DefaultService/Heartbeat',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            services_dot_default__service__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openapitools.services.defaultservice.DefaultService/Reset',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            services_dot_default__service__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Root(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openapitools.services.defaultservice.DefaultService/Root',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            services_dot_default__service__pb2.RootResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openapitools.services.defaultservice.DefaultService/Version',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            services_dot_default__service__pb2.VersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
