apiVersion: apps/v1
kind: Deployment
metadata:
  name: logservice
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logservice
  template:
    metadata:
      labels:
        app: logservice
    spec:
      serviceAccountName: logservice-serviceaccount
      containers:
        - command:
            - "logservice"
            - "logservice"
          image: {{ .Values.logService.image }}
          imagePullPolicy: IfNotPresent
          name: logservice
          ports:
            - containerPort: 50051
              name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: logservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
  selector:
    app: logservice
  type: ClusterIP

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: logservice-serviceaccount
  namespace: {{ .Values.namespace }}

---