name: Chroma Cross Version Test Reporter

on:
  push:
    branches:
      - main
      - team/hypothesis-tests
  pull_request:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 90
    strategy:
      matrix:
#        client-version: ['0.4.1','0.4.2','0.4.3','0.4.4','0.4.5','0.4.6','0.4.7','0.4.8','0.4.9','0.4.10','0.4.11','0.4.12','0.4.13','0.4.13','0.4.14','0.4.15','0.4.16','0.4.17','0.4.18','0.4.19']
        client-version: ['0.4.14','0.4.15','0.4.16','0.4.17','0.4.18','0.4.19']
#        server-version: ['0.4.1','0.4.2','0.4.3','0.4.4','0.4.5','0.4.6','0.4.7','0.4.8','0.4.9','0.4.10','0.4.11','0.4.12','0.4.13','0.4.13','0.4.14','0.4.15','0.4.16','0.4.17','0.4.18','0.4.19']
        server-version: ['0.4.14','0.4.15','0.4.16','0.4.17','0.4.18','0.4.19']
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/chross-version-tester/
        with:
          client-version: ${{ matrix.client-version }}
          server-version: ${{ matrix.server-version }}
          server-port: '8000'

